site_name: Whitebox
theme:
  name: material
  logo: img/logo-white.png
  favicon: img/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/git-alt
repo_url: https://github.com/squaredev-io/whitebox
repo_name: squaredev/whitebox
edit_uri: ""

nav:
  - Overview: index.md
  - Features: features.md
  - Tutorial:
      - tutorial/installation.md
      - tutorial/sdk.md
      - tutorial/metrics.md
      - tutorial/monitors_alerts.md

  - MLOps Monitoring Intro:
      - ml-monitoring.md
      - metric-definitions.md

  - sdk-docs.md

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
extra_css:
- css/termynal.css
- css/custom.css
- css/extra.css
extra_javascript:
  - js/termynal.js
  - js/custom.js
  - js/mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
